version: "3.9"

networks:
  sblk-net:
    name: sblk-net

volumes:
  db_data:
  sblk-seed-1:
  sblk-val-1:
  sblk-val-2:
  sblk-val-3:
  sblk-val-4:

services:
  seed-1:
    build: ./chains/sblk
    container_name: sblk-seed-1
    environment:
      CHAIN_ID: socialblock-testnet-1
      MONIKER: seed-1
      MIN_GAS_PRICE: 0.025usblk
    networks:
      - sblk-net
    volumes:
      - sblk-seed-1:/root/.simapp
    ports:
      - "26656:26656" # P2P
    restart: unless-stopped

  val-1:
    build: ./chains/sblk
    container_name: sblk-val-1
    environment:
      CHAIN_ID: socialblock-testnet-1
      MONIKER: val-1
      MIN_GAS_PRICE: 0.025usblk
      PERSISTENT_PEERS: ${PERSISTENT_PEERS}
    networks:
      - sblk-net
    volumes:
      - sblk-val-1:/root/.simapp
    depends_on:
      - seed-1
    ports:
      - "26657:26657" # RPC
      - "26666:26656" # P2P
      - "1317:1317"   # REST
      - "9090:9090"   # gRPC
    restart: unless-stopped

  val-2:
    build: ./chains/sblk
    container_name: sblk-val-2
    environment:
      CHAIN_ID: socialblock-testnet-1
      MONIKER: val-2
      MIN_GAS_PRICE: 0.025usblk
      PERSISTENT_PEERS: ${PERSISTENT_PEERS}
    networks:
      - sblk-net
    volumes:
      - sblk-val-2:/root/.simapp
    depends_on:
      - seed-1
    ports:
      - "26659:26657" # RPC
      - "26667:26656" # P2P
      - "1318:1317"   # REST
      - "9091:9090"   # gRPC
    restart: unless-stopped

  val-3:
    build: ./chains/sblk
    container_name: sblk-val-3
    environment:
      CHAIN_ID: socialblock-testnet-1
      MONIKER: val-3
      MIN_GAS_PRICE: 0.025usblk
      PERSISTENT_PEERS: ${PERSISTENT_PEERS}
    networks:
      - sblk-net
    volumes:
      - sblk-val-3:/root/.simapp
    depends_on:
      - seed-1
    ports:
      - "26661:26657" # RPC
      - "26668:26656" # P2P
      - "1319:1317"   # REST
      - "9092:9090"   # gRPC
    restart: unless-stopped

  val-4:
    build: ./chains/sblk
    container_name: sblk-val-4
    environment:
      CHAIN_ID: socialblock-testnet-1
      MONIKER: val-4
      MIN_GAS_PRICE: 0.025usblk
      PERSISTENT_PEERS: ${PERSISTENT_PEERS}
    networks:
      - sblk-net
    volumes:
      - sblk-val-4:/root/.simapp
    depends_on:
      - seed-1
    ports:
      - "26663:26657" # RPC
      - "26669:26656" # P2P
      - "1320:1317"   # REST
      - "9093:9090"   # gRPC
    restart: unless-stopped

  faucet:
    build: ./faucet
    container_name: sblk-faucet
    environment:
      RPC_HTTP: http://val-1:26657
      CHAIN_ID: socialblock-testnet-1
      DENOM: usblk
      BECH32_PREFIX: cosmos
      GAS_PRICE: 0.025usblk
      FAUCET_MNEMONIC: ${FAUCET_MNEMONIC}
    networks:
      - sblk-net
    ports:
      - "8000:8000"
    depends_on:
      - val-1
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: sblk-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - sblk-net
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  indexer:
    build: ./indexer/event-indexer
    container_name: sblk-indexer
    environment:
      INDEXER_RPC_WS: ${RPC_WS}
      INDEXER_DB_URL: ${INDEXER_DB_URL}
    networks:
      - sblk-net
    depends_on:
      - val-1
      - db
    restart: unless-stopped

  ai-arp-agent:
    build: ./ai/arp-agent
    container_name: sblk-arp-agent
    environment:
      ARP_AGENT_API_KEY: ${ARP_AGENT_API_KEY}
      SBLK_RPC: ${RPC_HTTP}
    networks:
      - sblk-net
    ports:
      - "8080:8080"
    depends_on:
      - val-1
    restart: unless-stopped

  explorer:
    image: nginx:alpine
    container_name: sblk-explorer
    networks:
      - sblk-net
    volumes:
      - ./explorer/pingpub:/usr/share/nginx/html:ro
      - ./explorer/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8088:80"
    depends_on:
      - val-1
    restart: unless-stopped
