version: "3.9"

services:
  node:
    build: ./chains/sblk
    container_name: sblk-node
    environment:
      CHAIN_ID: socialblock-devnet-1
      MONIKER: sblk-devnet
      MIN_GAS_PRICE: 0.025usblk
    ports:
      - "26657:26657"   # RPC
      - "26656:26656"   # P2P
      - "1317:1317"     # REST
      - "9090:9090"     # gRPC
    volumes:
      - sblkdata:/home/appuser/.socialblockd
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: sblk-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  indexer:
    build: ./indexer/event-indexer
    container_name: sblk-indexer
    environment:
      INDEXER_RPC_WS: ${RPC_WS}
      INDEXER_DB_URL: ${INDEXER_DB_URL}
    depends_on:
      - node
      - db
    restart: unless-stopped

  ai-arp-agent:
    build: ./ai/arp-agent
    container_name: sblk-arp-agent
    environment:
      ARP_AGENT_API_KEY: ${ARP_AGENT_API_KEY}
      SBLK_RPC: ${RPC_HTTP}
    ports:
      - "8080:8080"
    depends_on:
      - node
    restart: unless-stopped

  explorer:
    image: nginx:alpine
    container_name: sblk-explorer
    volumes:
      - ./explorer/pingpub:/usr/share/nginx/html:ro
    ports:
      - "8088:80"
    depends_on:
      - node
    restart: unless-stopped

volumes:
  db_data:
  sblkdata:
